docker:
  - image: docker.mirror.hashicorp.services/node:12
steps:
  - checkout
  - run:
      name: Push content to Algolia Index
      command: |
        if  [ "$CIRCLE_REPOSITORY_URL" != "git@github.com:hashicorp/nomad.git" ]; then
          echo "Not Nomad OSS Repo, not indexing Algolia"
          exit 0
        fi

        cd website/
        npm install
        node scripts/index_search_content.js
