executor: go
parameters:
  test_packages:
    type: string
    default: ""
  exclude_packages:
    type: string
    default: ""
  goarch:
    type: string
    default: "amd64"
environment:
  GOTEST_PKGS: "<< parameters.test_packages >>"
  GOTEST_PKGS_EXCLUDE: "<< parameters.exclude_packages >>"
  GOTESTARCH: "<< parameters.goarch >>"
steps:
  - checkout
  - run: apt-get update; apt-get install -y shellcheck sudo unzip
  - run: make deps
  - install-protoc
  - install-consul
  - install-vault
  - run-tests
  - store_test_results:
      path: /tmp/test-reports
  - store_artifacts:
      path: /tmp/test-reports
