// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: plugins/shared/structs/proto/recoverable_error.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecoverableError is used with a grpc Status to indicate if the error is one
// which is recoverable and can be reattempted by the client.
type RecoverableError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recoverable bool `protobuf:"varint,1,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
}

func (x *RecoverableError) Reset() {
	*x = RecoverableError{}
	mi := &file_plugins_shared_structs_proto_recoverable_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverableError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverableError) ProtoMessage() {}

func (x *RecoverableError) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_shared_structs_proto_recoverable_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverableError.ProtoReflect.Descriptor instead.
func (*RecoverableError) Descriptor() ([]byte, []int) {
	return file_plugins_shared_structs_proto_recoverable_error_proto_rawDescGZIP(), []int{0}
}

func (x *RecoverableError) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

var File_plugins_shared_structs_proto_recoverable_error_proto protoreflect.FileDescriptor

var file_plugins_shared_structs_proto_recoverable_error_proto_rawDesc = []byte{
	0x0a, 0x34, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x68, 0x61, 0x73, 0x68, 0x69, 0x63, 0x6f, 0x72,
	0x70, 0x2e, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x22, 0x34,
	0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x2e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugins_shared_structs_proto_recoverable_error_proto_rawDescOnce sync.Once
	file_plugins_shared_structs_proto_recoverable_error_proto_rawDescData = file_plugins_shared_structs_proto_recoverable_error_proto_rawDesc
)

func file_plugins_shared_structs_proto_recoverable_error_proto_rawDescGZIP() []byte {
	file_plugins_shared_structs_proto_recoverable_error_proto_rawDescOnce.Do(func() {
		file_plugins_shared_structs_proto_recoverable_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugins_shared_structs_proto_recoverable_error_proto_rawDescData)
	})
	return file_plugins_shared_structs_proto_recoverable_error_proto_rawDescData
}

var file_plugins_shared_structs_proto_recoverable_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plugins_shared_structs_proto_recoverable_error_proto_goTypes = []any{
	(*RecoverableError)(nil), // 0: hashicorp.nomad.plugins.shared.structs.RecoverableError
}
var file_plugins_shared_structs_proto_recoverable_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugins_shared_structs_proto_recoverable_error_proto_init() }
func file_plugins_shared_structs_proto_recoverable_error_proto_init() {
	if File_plugins_shared_structs_proto_recoverable_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugins_shared_structs_proto_recoverable_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugins_shared_structs_proto_recoverable_error_proto_goTypes,
		DependencyIndexes: file_plugins_shared_structs_proto_recoverable_error_proto_depIdxs,
		MessageInfos:      file_plugins_shared_structs_proto_recoverable_error_proto_msgTypes,
	}.Build()
	File_plugins_shared_structs_proto_recoverable_error_proto = out.File
	file_plugins_shared_structs_proto_recoverable_error_proto_rawDesc = nil
	file_plugins_shared_structs_proto_recoverable_error_proto_goTypes = nil
	file_plugins_shared_structs_proto_recoverable_error_proto_depIdxs = nil
}
