// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/shared/structs/proto/stats.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StatObject is a collection of statistics either exposed at the top
// level or via nested StatObjects.
type StatObject struct {
	// nested is a mapping of object name to a nested stats object.
	Nested map[string]*StatObject `protobuf:"bytes,1,rep,name=nested,proto3" json:"nested,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// attributes is a mapping of statistic name to its value.
	Attributes           map[string]*StatValue `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StatObject) Reset()         { *m = StatObject{} }
func (m *StatObject) String() string { return proto.CompactTextString(m) }
func (*StatObject) ProtoMessage()    {}
func (*StatObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_73a5e405c9cf442c, []int{0}
}
func (m *StatObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatObject.Unmarshal(m, b)
}
func (m *StatObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatObject.Marshal(b, m, deterministic)
}
func (dst *StatObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatObject.Merge(dst, src)
}
func (m *StatObject) XXX_Size() int {
	return xxx_messageInfo_StatObject.Size(m)
}
func (m *StatObject) XXX_DiscardUnknown() {
	xxx_messageInfo_StatObject.DiscardUnknown(m)
}

var xxx_messageInfo_StatObject proto.InternalMessageInfo

func (m *StatObject) GetNested() map[string]*StatObject {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *StatObject) GetAttributes() map[string]*StatValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// StatValue exposes the values of a particular statistic. The value may
// be of type double, integer, string or boolean. Numeric types can be
// exposed as a single value or as a fraction.
type StatValue struct {
	// float_numerator_val exposes a floating point value. If denominator
	// is set it is assumed to be a fractional value, otherwise it is a
	// scalar.
	FloatNumeratorVal   *wrappers.DoubleValue `protobuf:"bytes,1,opt,name=float_numerator_val,json=floatNumeratorVal,proto3" json:"float_numerator_val,omitempty"`
	FloatDenominatorVal *wrappers.DoubleValue `protobuf:"bytes,2,opt,name=float_denominator_val,json=floatDenominatorVal,proto3" json:"float_denominator_val,omitempty"`
	// int_numerator_val exposes a int value. If denominator
	// is set it is assumed to be a fractional value, otherwise it is a
	// scalar.
	IntNumeratorVal   *wrappers.Int64Value `protobuf:"bytes,3,opt,name=int_numerator_val,json=intNumeratorVal,proto3" json:"int_numerator_val,omitempty"`
	IntDenominatorVal *wrappers.Int64Value `protobuf:"bytes,4,opt,name=int_denominator_val,json=intDenominatorVal,proto3" json:"int_denominator_val,omitempty"`
	// string_val exposes a string value. These are likely annotations.
	StringVal *wrappers.StringValue `protobuf:"bytes,5,opt,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	// bool_val exposes a boolean statistic.
	BoolVal *wrappers.BoolValue `protobuf:"bytes,6,opt,name=bool_val,json=boolVal,proto3" json:"bool_val,omitempty"`
	// unit gives the unit type: °F, %, MHz, MB, etc.
	Unit string `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	// desc provides a human readable description of the statistic.
	Desc                 string   `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatValue) Reset()         { *m = StatValue{} }
func (m *StatValue) String() string { return proto.CompactTextString(m) }
func (*StatValue) ProtoMessage()    {}
func (*StatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_73a5e405c9cf442c, []int{1}
}
func (m *StatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatValue.Unmarshal(m, b)
}
func (m *StatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatValue.Marshal(b, m, deterministic)
}
func (dst *StatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatValue.Merge(dst, src)
}
func (m *StatValue) XXX_Size() int {
	return xxx_messageInfo_StatValue.Size(m)
}
func (m *StatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StatValue.DiscardUnknown(m)
}

var xxx_messageInfo_StatValue proto.InternalMessageInfo

func (m *StatValue) GetFloatNumeratorVal() *wrappers.DoubleValue {
	if m != nil {
		return m.FloatNumeratorVal
	}
	return nil
}

func (m *StatValue) GetFloatDenominatorVal() *wrappers.DoubleValue {
	if m != nil {
		return m.FloatDenominatorVal
	}
	return nil
}

func (m *StatValue) GetIntNumeratorVal() *wrappers.Int64Value {
	if m != nil {
		return m.IntNumeratorVal
	}
	return nil
}

func (m *StatValue) GetIntDenominatorVal() *wrappers.Int64Value {
	if m != nil {
		return m.IntDenominatorVal
	}
	return nil
}

func (m *StatValue) GetStringVal() *wrappers.StringValue {
	if m != nil {
		return m.StringVal
	}
	return nil
}

func (m *StatValue) GetBoolVal() *wrappers.BoolValue {
	if m != nil {
		return m.BoolVal
	}
	return nil
}

func (m *StatValue) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *StatValue) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*StatObject)(nil), "hashicorp.nomad.plugins.shared.structs.StatObject")
	proto.RegisterMapType((map[string]*StatValue)(nil), "hashicorp.nomad.plugins.shared.structs.StatObject.AttributesEntry")
	proto.RegisterMapType((map[string]*StatObject)(nil), "hashicorp.nomad.plugins.shared.structs.StatObject.NestedEntry")
	proto.RegisterType((*StatValue)(nil), "hashicorp.nomad.plugins.shared.structs.StatValue")
}

func init() {
	proto.RegisterFile("plugins/shared/structs/proto/stats.proto", fileDescriptor_stats_73a5e405c9cf442c)
}

var fileDescriptor_stats_73a5e405c9cf442c = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0x06, 0x70, 0x36, 0xdb, 0x24, 0xcd, 0xc9, 0x45, 0xed, 0x14, 0x61, 0x89, 0x22, 0xa1, 0x17,
	0x92, 0xab, 0x59, 0x8c, 0x7f, 0x10, 0x05, 0xc1, 0x50, 0xa9, 0xa2, 0x54, 0x49, 0x21, 0x17, 0xde,
	0x94, 0xd9, 0xec, 0x74, 0x33, 0x3a, 0x3b, 0xb3, 0xcc, 0x9c, 0xa9, 0xf4, 0x91, 0x7c, 0x28, 0xdf,
	0x45, 0x76, 0x66, 0x93, 0xa6, 0x5b, 0xc5, 0xd6, 0xab, 0x9c, 0x4c, 0xf2, 0xfd, 0xbe, 0xb3, 0xcc,
	0xc2, 0xa4, 0x92, 0xae, 0x10, 0xca, 0xa6, 0x76, 0xc5, 0x0c, 0xcf, 0x53, 0x8b, 0xc6, 0x2d, 0xd1,
	0xa6, 0x95, 0xd1, 0xa8, 0x53, 0x8b, 0x0c, 0x2d, 0xf5, 0x33, 0x79, 0xbc, 0x62, 0x76, 0x25, 0x96,
	0xda, 0x54, 0x54, 0xe9, 0x92, 0xe5, 0xb4, 0x49, 0xd2, 0x90, 0xa4, 0x4d, 0x72, 0xf4, 0xa8, 0xd0,
	0xba, 0x90, 0x3c, 0x08, 0x99, 0x3b, 0x4f, 0x7f, 0x18, 0x56, 0x55, 0xdc, 0x34, 0xce, 0xe1, 0xcf,
	0x18, 0xe0, 0x14, 0x19, 0x7e, 0xce, 0xbe, 0xf1, 0x25, 0x92, 0x05, 0xf4, 0x14, 0xb7, 0xc8, 0xf3,
	0x24, 0x1a, 0xc7, 0x93, 0xe1, 0xf4, 0x0d, 0xbd, 0x5d, 0x0f, 0xbd, 0x32, 0xe8, 0x89, 0x07, 0xde,
	0x29, 0x34, 0x97, 0xf3, 0x46, 0x23, 0x19, 0x00, 0x43, 0x34, 0x22, 0x73, 0xc8, 0x6d, 0xd2, 0xf1,
	0xf6, 0xec, 0x3f, 0xec, 0xb7, 0x1b, 0x24, 0xf8, 0x5b, 0xea, 0xa8, 0x84, 0xe1, 0x56, 0x35, 0xb9,
	0x07, 0xf1, 0x77, 0x7e, 0x99, 0x44, 0xe3, 0x68, 0x32, 0x98, 0xd7, 0x23, 0x79, 0x0f, 0xdd, 0x0b,
	0x26, 0x1d, 0x4f, 0x3a, 0xe3, 0x68, 0x32, 0x9c, 0x4e, 0xef, 0xde, 0x3f, 0x0f, 0xc0, 0xab, 0xce,
	0xcb, 0x68, 0x54, 0xc1, 0x5e, 0x6b, 0x9b, 0x3f, 0x54, 0x1e, 0x5f, 0xaf, 0x7c, 0x72, 0x97, 0xca,
	0x45, 0x1d, 0xdc, 0x6a, 0x3c, 0xfc, 0x15, 0xc3, 0x60, 0xf3, 0x03, 0xf9, 0x04, 0x07, 0xe7, 0x52,
	0x33, 0x3c, 0x53, 0xae, 0xe4, 0x86, 0xa1, 0x36, 0x67, 0x17, 0x4c, 0xfa, 0xf2, 0xe1, 0xf4, 0x21,
	0x0d, 0xf7, 0x4e, 0xd7, 0xf7, 0x4e, 0x8f, 0xb4, 0xcb, 0x24, 0x0f, 0xe6, 0xbe, 0x0f, 0x9e, 0xac,
	0x73, 0x0b, 0x26, 0xc9, 0x17, 0xb8, 0x1f, 0xb4, 0x9c, 0x2b, 0x5d, 0x0a, 0xb5, 0xf1, 0x3a, 0xb7,
	0xf0, 0xc2, 0x22, 0x47, 0x57, 0xc9, 0x5a, 0x3c, 0x86, 0x7d, 0xa1, 0xda, 0xdb, 0xc5, 0x5e, 0x7b,
	0x70, 0x43, 0xfb, 0xa0, 0xf0, 0xc5, 0xb3, 0x80, 0xed, 0x09, 0x75, 0x7d, 0xb5, 0x8f, 0x70, 0x50,
	0x43, 0xed, 0xc5, 0x76, 0xfe, 0x4d, 0xd5, 0x0b, 0xb4, 0xb6, 0x7a, 0x0d, 0x60, 0xd1, 0x08, 0x55,
	0x78, 0xa3, 0xfb, 0x97, 0x87, 0x3b, 0xf5, 0x7f, 0x09, 0xc8, 0xc0, 0xae, 0xbf, 0x90, 0xe7, 0xb0,
	0x9b, 0x69, 0x2d, 0x7d, 0xb4, 0xe7, 0xa3, 0xa3, 0x1b, 0xd1, 0x99, 0xd6, 0x32, 0x04, 0xfb, 0x59,
	0x18, 0x09, 0x81, 0x1d, 0xa7, 0x04, 0x26, 0x7d, 0xff, 0x5e, 0xf8, 0xb9, 0x3e, 0xcb, 0xb9, 0x5d,
	0x26, 0xbb, 0xe1, 0xac, 0x9e, 0x67, 0xfd, 0xaf, 0xdd, 0xc0, 0xf4, 0xfc, 0xc7, 0xd3, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x7d, 0x1d, 0x2d, 0xe3, 0x0f, 0x04, 0x00, 0x00,
}
