# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - custom-windows-medium
    - windows-2019-16core
    - custom-linux-xxl-nomad-20.04
    - custom-linux-xl-nomad-22.04
