# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    labels:
      - "theme/dependencies"
    schedule:
      interval: "cron"
      cronjob: "0 9 15 * *" # once a month, mid-month
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: "/api"
    labels:
      - "theme/dependencies"
      - "theme/api"
    schedule:
      interval: "cron"
      cronjob: "0 9 15 * *" # once a month, mid-month
    groups:
      go-api:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/ui"
    labels:
      - "theme/dependencies"
      - "theme/ui"
    schedule:
      interval: "cron"
      cronjob: "0 9 15 * *" # once a month, mid-month
    groups:
      ui-dev:
         patterns:
           - "*"
         dependency-type: "development"
      ui-prod:
         patterns:
           - "*"
         dependency-type: "production"
