packages:
  - ui

autoInstallPeers: false
# strictPeerDependencies: true # this is temporarily disabled. We should re-enable this once those issues are resolved.
resolvePeersFromWorkspaceRoot: false
publicHoistPattern:
  - ember-source
verifyDepsBeforeRun: install

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  "@glimmer/component": ^2.0.0
  ansi-html@<0.0.8: '>=0.0.8'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tmp@<=0.2.3: '>=0.2.4'
