packages:
  - ui
overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  "@ember/test-waiters": ^4.1.1
  "@glimmer/component": ^2.0.0
  ansi-html@<0.0.8: '>=0.0.8'
  braces@<3.0.3: '>=3.0.3'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  flatted@<3.4.0: '>=3.4.0'
  micromatch@<4.0.8: '>=4.0.8'
  on-headers@<1.1.0: '>=1.1.0'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  rollup@<2.79.2: '>=2.79.2'
  rollup@<2.80.0: '>=2.80.0'
  tmp@<=0.2.3: '>=0.2.4'
  yauzl@<3.2.1: '>=3.2.1'
