#!/usr/bin/env bash

if [ ! -f version/version.go ]; then
  echo 'No version/version.go file here. Are you in the nomad/ repo root?'
  exit 1
fi

if ! git diff-index --quiet HEAD --; then
  echo 'need a clean worktree; try: `git clone $PWD /tmp/nomad && cd /tmp/nomad`'
  exit 1
fi
