#!/usr/bin/env bash

if [ ! -f version/version.go ]; then
  echo 'No version/version.go file here. Are you in the nomad/ repo root?'
  exit 1
fi

if ! git diff-index --quiet HEAD --; then
  tput bold setaf 3 # yellow
  echo '!! Need a clean worktree !!'
  tput sgr0 # reset
  echo 'If you run this here, your local git will be modified.'
  echo 'Run this to get a fresh, separate worktree:'
  tput setaf 2 # green
  echo '  git clone $PWD /tmp/nomad && cd /tmp/nomad'
  tput sgr0
  echo 'then try again.'
  exit 1
fi
