name: HashiCorp PR Bot
on: push
jobs:
  check_links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
        working-directory: ./website
      - uses: ./.github/actions/check_links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          baseUrl: ${{ github.event.deployment.payload.environment_url }}
