parameters:
  version:
    type: string
    default: 1.2.4
steps:
  - run:
      name: Install Vault << parameters.version >>
      command: |
        curl -SL --fail -o /tmp/vault.zip https://releases.hashicorp.com/vault/<< parameters.version >>/vault_<< parameters.version>>_linux_amd64.zip
        sudo unzip -d /usr/local/bin /tmp/vault.zip
        rm -rf /tmp/vault*
