// Code generated by "stringer -trimprefix=Event -output string_eventid.go -linecomment -type=WindowsEventId"; DO NOT EDIT.

package winsvc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventUnknown-0]
	_ = x[EventServiceStarting-1]
	_ = x[EventServiceStarted-2]
	_ = x[EventServiceStopped-3]
	_ = x[EventLogMessage-4]
}

const _WindowsEventId_name = "unknown eventservice startingservice startedservice stoppedlog message"

var _WindowsEventId_index = [...]uint8{0, 13, 29, 44, 59, 70}

func (i WindowsEventId) String() string {
	if i >= WindowsEventId(len(_WindowsEventId_index)-1) {
		return "WindowsEventId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WindowsEventId_name[_WindowsEventId_index[i]:_WindowsEventId_index[i+1]]
}
