/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.3
 * Contact: support@hashicorp.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package testclient

import (
	"encoding/json"
)

// VolumeMount struct for VolumeMount
type VolumeMount struct {
	Destination *string `json:"Destination,omitempty"`
	PropagationMode *string `json:"PropagationMode,omitempty"`
	ReadOnly *bool `json:"ReadOnly,omitempty"`
	Volume *string `json:"Volume,omitempty"`
}

// NewVolumeMount instantiates a new VolumeMount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeMount() *VolumeMount {
	this := VolumeMount{}
	return &this
}

// NewVolumeMountWithDefaults instantiates a new VolumeMount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeMountWithDefaults() *VolumeMount {
	this := VolumeMount{}
	return &this
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *VolumeMount) GetDestination() string {
	if o == nil || o.Destination == nil {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeMount) GetDestinationOk() (*string, bool) {
	if o == nil || o.Destination == nil {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *VolumeMount) HasDestination() bool {
	if o != nil && o.Destination != nil {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *VolumeMount) SetDestination(v string) {
	o.Destination = &v
}

// GetPropagationMode returns the PropagationMode field value if set, zero value otherwise.
func (o *VolumeMount) GetPropagationMode() string {
	if o == nil || o.PropagationMode == nil {
		var ret string
		return ret
	}
	return *o.PropagationMode
}

// GetPropagationModeOk returns a tuple with the PropagationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeMount) GetPropagationModeOk() (*string, bool) {
	if o == nil || o.PropagationMode == nil {
		return nil, false
	}
	return o.PropagationMode, true
}

// HasPropagationMode returns a boolean if a field has been set.
func (o *VolumeMount) HasPropagationMode() bool {
	if o != nil && o.PropagationMode != nil {
		return true
	}

	return false
}

// SetPropagationMode gets a reference to the given string and assigns it to the PropagationMode field.
func (o *VolumeMount) SetPropagationMode(v string) {
	o.PropagationMode = &v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *VolumeMount) GetReadOnly() bool {
	if o == nil || o.ReadOnly == nil {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeMount) GetReadOnlyOk() (*bool, bool) {
	if o == nil || o.ReadOnly == nil {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *VolumeMount) HasReadOnly() bool {
	if o != nil && o.ReadOnly != nil {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *VolumeMount) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *VolumeMount) GetVolume() string {
	if o == nil || o.Volume == nil {
		var ret string
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeMount) GetVolumeOk() (*string, bool) {
	if o == nil || o.Volume == nil {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *VolumeMount) HasVolume() bool {
	if o != nil && o.Volume != nil {
		return true
	}

	return false
}

// SetVolume gets a reference to the given string and assigns it to the Volume field.
func (o *VolumeMount) SetVolume(v string) {
	o.Volume = &v
}

func (o VolumeMount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Destination != nil {
		toSerialize["Destination"] = o.Destination
	}
	if o.PropagationMode != nil {
		toSerialize["PropagationMode"] = o.PropagationMode
	}
	if o.ReadOnly != nil {
		toSerialize["ReadOnly"] = o.ReadOnly
	}
	if o.Volume != nil {
		toSerialize["Volume"] = o.Volume
	}
	return json.Marshal(toSerialize)
}

type NullableVolumeMount struct {
	value *VolumeMount
	isSet bool
}

func (v NullableVolumeMount) Get() *VolumeMount {
	return v.value
}

func (v *NullableVolumeMount) Set(val *VolumeMount) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeMount) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeMount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeMount(val *VolumeMount) *NullableVolumeMount {
	return &NullableVolumeMount{value: val, isSet: true}
}

func (v NullableVolumeMount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeMount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


