/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.3
 * Contact: support@hashicorp.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package testclient

import (
	"encoding/json"
)

// NamespaceListRequest struct for NamespaceListRequest
type NamespaceListRequest struct {
	AllowStale    *bool   `json:"AllowStale,omitempty"`
	AuthToken     *string `json:"AuthToken,omitempty"`
	Forwarded     *bool   `json:"Forwarded,omitempty"`
	MaxQueryTime  *int64  `json:"MaxQueryTime,omitempty"`
	MinQueryIndex *int32  `json:"MinQueryIndex,omitempty"`
	Namespace     *string `json:"Namespace,omitempty"`
	NextToken     *string `json:"NextToken,omitempty"`
	PerPage       *int32  `json:"PerPage,omitempty"`
	Prefix        *string `json:"Prefix,omitempty"`
	Region        *string `json:"Region,omitempty"`
}

// NewNamespaceListRequest instantiates a new NamespaceListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceListRequest() *NamespaceListRequest {
	this := NamespaceListRequest{}
	return &this
}

// NewNamespaceListRequestWithDefaults instantiates a new NamespaceListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceListRequestWithDefaults() *NamespaceListRequest {
	this := NamespaceListRequest{}
	return &this
}

// GetAllowStale returns the AllowStale field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetAllowStale() bool {
	if o == nil || o.AllowStale == nil {
		var ret bool
		return ret
	}
	return *o.AllowStale
}

// GetAllowStaleOk returns a tuple with the AllowStale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetAllowStaleOk() (*bool, bool) {
	if o == nil || o.AllowStale == nil {
		return nil, false
	}
	return o.AllowStale, true
}

// HasAllowStale returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasAllowStale() bool {
	if o != nil && o.AllowStale != nil {
		return true
	}

	return false
}

// SetAllowStale gets a reference to the given bool and assigns it to the AllowStale field.
func (o *NamespaceListRequest) SetAllowStale(v bool) {
	o.AllowStale = &v
}

// GetAuthToken returns the AuthToken field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetAuthToken() string {
	if o == nil || o.AuthToken == nil {
		var ret string
		return ret
	}
	return *o.AuthToken
}

// GetAuthTokenOk returns a tuple with the AuthToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetAuthTokenOk() (*string, bool) {
	if o == nil || o.AuthToken == nil {
		return nil, false
	}
	return o.AuthToken, true
}

// HasAuthToken returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasAuthToken() bool {
	if o != nil && o.AuthToken != nil {
		return true
	}

	return false
}

// SetAuthToken gets a reference to the given string and assigns it to the AuthToken field.
func (o *NamespaceListRequest) SetAuthToken(v string) {
	o.AuthToken = &v
}

// GetForwarded returns the Forwarded field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetForwarded() bool {
	if o == nil || o.Forwarded == nil {
		var ret bool
		return ret
	}
	return *o.Forwarded
}

// GetForwardedOk returns a tuple with the Forwarded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetForwardedOk() (*bool, bool) {
	if o == nil || o.Forwarded == nil {
		return nil, false
	}
	return o.Forwarded, true
}

// HasForwarded returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasForwarded() bool {
	if o != nil && o.Forwarded != nil {
		return true
	}

	return false
}

// SetForwarded gets a reference to the given bool and assigns it to the Forwarded field.
func (o *NamespaceListRequest) SetForwarded(v bool) {
	o.Forwarded = &v
}

// GetMaxQueryTime returns the MaxQueryTime field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetMaxQueryTime() int64 {
	if o == nil || o.MaxQueryTime == nil {
		var ret int64
		return ret
	}
	return *o.MaxQueryTime
}

// GetMaxQueryTimeOk returns a tuple with the MaxQueryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetMaxQueryTimeOk() (*int64, bool) {
	if o == nil || o.MaxQueryTime == nil {
		return nil, false
	}
	return o.MaxQueryTime, true
}

// HasMaxQueryTime returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasMaxQueryTime() bool {
	if o != nil && o.MaxQueryTime != nil {
		return true
	}

	return false
}

// SetMaxQueryTime gets a reference to the given int64 and assigns it to the MaxQueryTime field.
func (o *NamespaceListRequest) SetMaxQueryTime(v int64) {
	o.MaxQueryTime = &v
}

// GetMinQueryIndex returns the MinQueryIndex field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetMinQueryIndex() int32 {
	if o == nil || o.MinQueryIndex == nil {
		var ret int32
		return ret
	}
	return *o.MinQueryIndex
}

// GetMinQueryIndexOk returns a tuple with the MinQueryIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetMinQueryIndexOk() (*int32, bool) {
	if o == nil || o.MinQueryIndex == nil {
		return nil, false
	}
	return o.MinQueryIndex, true
}

// HasMinQueryIndex returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasMinQueryIndex() bool {
	if o != nil && o.MinQueryIndex != nil {
		return true
	}

	return false
}

// SetMinQueryIndex gets a reference to the given int32 and assigns it to the MinQueryIndex field.
func (o *NamespaceListRequest) SetMinQueryIndex(v int32) {
	o.MinQueryIndex = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *NamespaceListRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetNextToken() string {
	if o == nil || o.NextToken == nil {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetNextTokenOk() (*string, bool) {
	if o == nil || o.NextToken == nil {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasNextToken() bool {
	if o != nil && o.NextToken != nil {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *NamespaceListRequest) SetNextToken(v string) {
	o.NextToken = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetPerPage() int32 {
	if o == nil || o.PerPage == nil {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetPerPageOk() (*int32, bool) {
	if o == nil || o.PerPage == nil {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasPerPage() bool {
	if o != nil && o.PerPage != nil {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *NamespaceListRequest) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetPrefix() string {
	if o == nil || o.Prefix == nil {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetPrefixOk() (*string, bool) {
	if o == nil || o.Prefix == nil {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasPrefix() bool {
	if o != nil && o.Prefix != nil {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *NamespaceListRequest) SetPrefix(v string) {
	o.Prefix = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *NamespaceListRequest) GetRegion() string {
	if o == nil || o.Region == nil {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceListRequest) GetRegionOk() (*string, bool) {
	if o == nil || o.Region == nil {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *NamespaceListRequest) HasRegion() bool {
	if o != nil && o.Region != nil {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *NamespaceListRequest) SetRegion(v string) {
	o.Region = &v
}

func (o NamespaceListRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowStale != nil {
		toSerialize["AllowStale"] = o.AllowStale
	}
	if o.AuthToken != nil {
		toSerialize["AuthToken"] = o.AuthToken
	}
	if o.Forwarded != nil {
		toSerialize["Forwarded"] = o.Forwarded
	}
	if o.MaxQueryTime != nil {
		toSerialize["MaxQueryTime"] = o.MaxQueryTime
	}
	if o.MinQueryIndex != nil {
		toSerialize["MinQueryIndex"] = o.MinQueryIndex
	}
	if o.Namespace != nil {
		toSerialize["Namespace"] = o.Namespace
	}
	if o.NextToken != nil {
		toSerialize["NextToken"] = o.NextToken
	}
	if o.PerPage != nil {
		toSerialize["PerPage"] = o.PerPage
	}
	if o.Prefix != nil {
		toSerialize["Prefix"] = o.Prefix
	}
	if o.Region != nil {
		toSerialize["Region"] = o.Region
	}
	return json.Marshal(toSerialize)
}

type NullableNamespaceListRequest struct {
	value *NamespaceListRequest
	isSet bool
}

func (v NullableNamespaceListRequest) Get() *NamespaceListRequest {
	return v.value
}

func (v *NullableNamespaceListRequest) Set(val *NamespaceListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceListRequest(val *NamespaceListRequest) *NullableNamespaceListRequest {
	return &NullableNamespaceListRequest{value: val, isSet: true}
}

func (v NullableNamespaceListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
