// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client/logmon/v0/proto/logmon.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartRequest struct {
	LogDir               string   `protobuf:"bytes,1,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	StdoutFileName       string   `protobuf:"bytes,2,opt,name=stdout_file_name,json=stdoutFileName,proto3" json:"stdout_file_name,omitempty"`
	StderrFileName       string   `protobuf:"bytes,3,opt,name=stderr_file_name,json=stderrFileName,proto3" json:"stderr_file_name,omitempty"`
	MaxFiles             uint32   `protobuf:"varint,4,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"`
	MaxFileSizeMb        uint32   `protobuf:"varint,5,opt,name=max_file_size_mb,json=maxFileSizeMb,proto3" json:"max_file_size_mb,omitempty"`
	StdoutFifo           string   `protobuf:"bytes,6,opt,name=stdout_fifo,json=stdoutFifo,proto3" json:"stdout_fifo,omitempty"`
	StderrFifo           string   `protobuf:"bytes,7,opt,name=stderr_fifo,json=stderrFifo,proto3" json:"stderr_fifo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd38ec803e108b, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetLogDir() string {
	if m != nil {
		return m.LogDir
	}
	return ""
}

func (m *StartRequest) GetStdoutFileName() string {
	if m != nil {
		return m.StdoutFileName
	}
	return ""
}

func (m *StartRequest) GetStderrFileName() string {
	if m != nil {
		return m.StderrFileName
	}
	return ""
}

func (m *StartRequest) GetMaxFiles() uint32 {
	if m != nil {
		return m.MaxFiles
	}
	return 0
}

func (m *StartRequest) GetMaxFileSizeMb() uint32 {
	if m != nil {
		return m.MaxFileSizeMb
	}
	return 0
}

func (m *StartRequest) GetStdoutFifo() string {
	if m != nil {
		return m.StdoutFifo
	}
	return ""
}

func (m *StartRequest) GetStderrFifo() string {
	if m != nil {
		return m.StderrFifo
	}
	return ""
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd38ec803e108b, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd38ec803e108b, []int{2}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd38ec803e108b, []int{3}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartRequest)(nil), "hashicorp.nomad.client.logmon.proto.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "hashicorp.nomad.client.logmon.proto.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "hashicorp.nomad.client.logmon.proto.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "hashicorp.nomad.client.logmon.proto.StopResponse")
}

func init() {
	proto.RegisterFile("client/logmon/v0/proto/logmon.proto", fileDescriptor_30bd38ec803e108b)
}

var fileDescriptor_30bd38ec803e108b = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbf, 0x6e, 0xf2, 0x30,
	0x14, 0xc5, 0xbf, 0xf0, 0x41, 0x28, 0x97, 0x86, 0x22, 0x2f, 0x8d, 0xe8, 0x50, 0x14, 0x86, 0x32,
	0x85, 0x3f, 0x7d, 0x83, 0xaa, 0xea, 0x54, 0x3a, 0xc0, 0xd6, 0x25, 0x32, 0xe0, 0x04, 0x4b, 0xb1,
	0x6f, 0x6a, 0x9b, 0x0a, 0xb1, 0xf6, 0x69, 0xfb, 0x16, 0x55, 0x1c, 0x13, 0x31, 0xc2, 0x64, 0xdd,
	0x7b, 0x7e, 0x47, 0xf7, 0xf8, 0xc0, 0x68, 0x93, 0x73, 0x26, 0xcd, 0x24, 0xc7, 0x4c, 0xa0, 0x9c,
	0x7c, 0x4f, 0x27, 0x85, 0x42, 0x83, 0x6e, 0x8e, 0xed, 0x40, 0x46, 0x3b, 0xaa, 0x77, 0x7c, 0x83,
	0xaa, 0x88, 0x25, 0x0a, 0xba, 0x8d, 0x2b, 0x53, 0x7c, 0x0e, 0x45, 0x3f, 0x0d, 0xb8, 0x5d, 0x19,
	0xaa, 0xcc, 0x92, 0x7d, 0xed, 0x99, 0x36, 0xe4, 0x1e, 0xda, 0x39, 0x66, 0xc9, 0x96, 0xab, 0xd0,
	0x1b, 0x7a, 0xe3, 0xce, 0xd2, 0xcf, 0x31, 0x7b, 0xe5, 0x8a, 0x8c, 0xa1, 0xaf, 0xcd, 0x16, 0xf7,
	0x26, 0x49, 0x79, 0xce, 0x12, 0x49, 0x05, 0x0b, 0x1b, 0x96, 0xe8, 0x55, 0xfb, 0x37, 0x9e, 0xb3,
	0x0f, 0x2a, 0x98, 0x23, 0x99, 0x52, 0x67, 0xe4, 0xff, 0x9a, 0x64, 0x4a, 0xd5, 0xe4, 0x03, 0x74,
	0x04, 0x3d, 0x58, 0x4c, 0x87, 0xcd, 0xa1, 0x37, 0x0e, 0x96, 0x37, 0x82, 0x1e, 0x4a, 0x5d, 0x93,
	0x27, 0xe8, 0x9f, 0xc4, 0x44, 0xf3, 0x23, 0x4b, 0xc4, 0x3a, 0x6c, 0x59, 0x26, 0x70, 0xcc, 0x8a,
	0x1f, 0xd9, 0x62, 0x4d, 0x1e, 0xa1, 0x5b, 0x27, 0x4b, 0x31, 0xf4, 0xed, 0x29, 0x38, 0x85, 0x4a,
	0xd1, 0x01, 0x55, 0xa0, 0x14, 0xc3, 0x76, 0x0d, 0xd8, 0x2c, 0x29, 0x46, 0x77, 0x10, 0xb8, 0x12,
	0x74, 0x81, 0x52, 0xb3, 0x28, 0x80, 0xee, 0xca, 0x60, 0xe1, 0x4a, 0x89, 0x7a, 0x65, 0x49, 0xe5,
	0x58, 0xc9, 0xf3, 0x5f, 0x0f, 0xfc, 0x77, 0xcc, 0x16, 0x28, 0x49, 0x01, 0x2d, 0x6b, 0x25, 0xb3,
	0xf8, 0x82, 0xbe, 0xe3, 0xf3, 0xae, 0x07, 0xf3, 0x6b, 0x2c, 0x2e, 0xd9, 0x3f, 0x22, 0xa0, 0x59,
	0x86, 0x21, 0xd3, 0x0b, 0xdd, 0xf5, 0x37, 0x06, 0xb3, 0x2b, 0x1c, 0xa7, 0x73, 0x2f, 0xed, 0xcf,
	0x96, 0xdd, 0xaf, 0x7d, 0xfb, 0x3c, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x15, 0xef, 0xf4,
	0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogMonClient is the client API for LogMon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogMonClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type logMonClient struct {
	cc grpc.ClientConnInterface
}

func NewLogMonClient(cc grpc.ClientConnInterface) LogMonClient {
	return &logMonClient{cc}
}

func (c *logMonClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.client.logmon.proto.LogMon/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logMonClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.client.logmon.proto.LogMon/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogMonServer is the server API for LogMon service.
type LogMonServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
}

// UnimplementedLogMonServer can be embedded to have forward compatible implementations.
type UnimplementedLogMonServer struct {
}

func (*UnimplementedLogMonServer) Start(ctx context.Context, req *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedLogMonServer) Stop(ctx context.Context, req *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

func RegisterLogMonServer(s *grpc.Server, srv LogMonServer) {
	s.RegisterService(&_LogMon_serviceDesc, srv)
}

func _LogMon_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogMonServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.client.logmon.proto.LogMon/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogMonServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogMon_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogMonServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.client.logmon.proto.LogMon/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogMonServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogMon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad.client.logmon.proto.LogMon",
	HandlerType: (*LogMonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _LogMon_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _LogMon_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/logmon/v0/proto/logmon.proto",
}
