region            = "us-east-1"
ami               = "ami-a780afdc"
instance_type     = "t2.medium"
key_name          = "KEY_NAME"
server_count      = "1"
client_count      = "4"
cluster_tag_value = "auto-join"
