# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: jira-transition
description: Transition state of JIRA issue
inputs:
  issue:
    required: true
    description: JIRA issue to transition
  resolution:
    required: false
    description: Resolution name to apply to issue
  transition:
    required: true
    description: Transition name to apply to issue
  fixed-version:
    required: false
    description: Version fixed (only used if resolution set. Use 'auto' for detection in nomad.)
  timeline-url:
    required: false
    description: GitHub API issue timeline URL (required if fixed-version is set to 'auto')
  project:
    required: false
    description: JIRA project (required for setting fixed-version)
    default: NMD

runs:
  using: composite
  steps:
  - name: Transition JIRA issue
    shell: bash
    run: ./.github/actions/jira/transition/jira-transition.bash
    env:
      ISSUE: ${{ inputs.issue }}
      TRANSITION: ${{ inputs.transition }}
      RESOLUTION: ${{ inputs.resolution }}
      FIXED_VERSION: ${{ inputs.fixed-version }}
      TIMELINE_URL: ${{ inputs.timeline-url }}
      PROJECT: ${{ inputs.project }}
