// Code generated by protoc-gen-go. DO NOT EDIT.
// source: docklog.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartRequest struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StdoutFifo           string   `protobuf:"bytes,3,opt,name=stdout_fifo,json=stdoutFifo,proto3" json:"stdout_fifo,omitempty"`
	StderrFifo           string   `protobuf:"bytes,4,opt,name=stderr_fifo,json=stderrFifo,proto3" json:"stderr_fifo,omitempty"`
	TlsCert              string   `protobuf:"bytes,5,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	TlsKey               string   `protobuf:"bytes,6,opt,name=tls_key,json=tlsKey,proto3" json:"tls_key,omitempty"`
	TlsCa                string   `protobuf:"bytes,7,opt,name=tls_ca,json=tlsCa,proto3" json:"tls_ca,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_docklog_6cb3edde8d295224, []int{0}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *StartRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *StartRequest) GetStdoutFifo() string {
	if m != nil {
		return m.StdoutFifo
	}
	return ""
}

func (m *StartRequest) GetStderrFifo() string {
	if m != nil {
		return m.StderrFifo
	}
	return ""
}

func (m *StartRequest) GetTlsCert() string {
	if m != nil {
		return m.TlsCert
	}
	return ""
}

func (m *StartRequest) GetTlsKey() string {
	if m != nil {
		return m.TlsKey
	}
	return ""
}

func (m *StartRequest) GetTlsCa() string {
	if m != nil {
		return m.TlsCa
	}
	return ""
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_docklog_6cb3edde8d295224, []int{1}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_docklog_6cb3edde8d295224, []int{2}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_docklog_6cb3edde8d295224, []int{3}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (dst *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(dst, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartRequest)(nil), "hashicorp.nomad.drivers.docker.docklog.proto.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "hashicorp.nomad.drivers.docker.docklog.proto.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "hashicorp.nomad.drivers.docker.docklog.proto.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "hashicorp.nomad.drivers.docker.docklog.proto.StopResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocklogClient is the client API for Docklog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocklogClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type docklogClient struct {
	cc *grpc.ClientConn
}

func NewDocklogClient(cc *grpc.ClientConn) DocklogClient {
	return &docklogClient{cc}
}

func (c *docklogClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.drivers.docker.docklog.proto.Docklog/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docklogClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.drivers.docker.docklog.proto.Docklog/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocklogServer is the server API for Docklog service.
type DocklogServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
}

func RegisterDocklogServer(s *grpc.Server, srv DocklogServer) {
	s.RegisterService(&_Docklog_serviceDesc, srv)
}

func _Docklog_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocklogServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.drivers.docker.docklog.proto.Docklog/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocklogServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Docklog_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocklogServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.drivers.docker.docklog.proto.Docklog/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocklogServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Docklog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad.drivers.docker.docklog.proto.Docklog",
	HandlerType: (*DocklogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Docklog_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Docklog_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docklog.proto",
}

func init() { proto.RegisterFile("docklog.proto", fileDescriptor_docklog_6cb3edde8d295224) }

var fileDescriptor_docklog_6cb3edde8d295224 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xb1, 0x4e, 0xf3, 0x40,
	0x10, 0x84, 0x7f, 0xe7, 0x8f, 0xed, 0xb0, 0x49, 0x40, 0x3a, 0x09, 0x61, 0xd2, 0x00, 0xae, 0x28,
	0xd0, 0x15, 0x50, 0x11, 0x3a, 0x40, 0x48, 0x88, 0x2e, 0xe9, 0x68, 0x2c, 0xe3, 0x3b, 0x93, 0x53,
	0x8c, 0xd7, 0xec, 0x6d, 0x90, 0x52, 0x21, 0xf1, 0x02, 0xbc, 0x1f, 0x4f, 0x83, 0x7c, 0x36, 0x16,
	0x94, 0x49, 0x65, 0xef, 0xcc, 0x37, 0xa7, 0x9d, 0x85, 0xb1, 0xc2, 0x6c, 0x59, 0xe0, 0xb3, 0xac,
	0x08, 0x19, 0xc5, 0xd9, 0x22, 0xb5, 0x0b, 0x93, 0x21, 0x55, 0xb2, 0xc4, 0x97, 0x54, 0x49, 0x45,
	0xe6, 0x4d, 0x93, 0x95, 0x35, 0xa6, 0x49, 0xfe, 0xa1, 0xe3, 0x2f, 0x0f, 0x46, 0x73, 0x4e, 0x89,
	0x67, 0xfa, 0x75, 0xa5, 0x2d, 0x8b, 0x09, 0x0c, 0x74, 0xa9, 0x2a, 0x34, 0x25, 0x47, 0xde, 0xb1,
	0x77, 0xba, 0x33, 0xeb, 0x66, 0x71, 0x02, 0xa3, 0x0c, 0x4b, 0x4e, 0x4d, 0xa9, 0x29, 0x31, 0x2a,
	0xea, 0x39, 0x7f, 0xd8, 0x69, 0xf7, 0x4a, 0x1c, 0xc1, 0xd0, 0xb2, 0xc2, 0x15, 0x27, 0xb9, 0xc9,
	0x31, 0xfa, 0xef, 0x08, 0x68, 0xa4, 0x3b, 0x93, 0x63, 0x0b, 0x68, 0xa2, 0x06, 0xe8, 0x77, 0x80,
	0x26, 0x72, 0xc0, 0x21, 0x0c, 0xb8, 0xb0, 0x49, 0xa6, 0x89, 0x23, 0xdf, 0xb9, 0x21, 0x17, 0xf6,
	0x46, 0x13, 0x8b, 0x03, 0xa8, 0x7f, 0x93, 0xa5, 0x5e, 0x47, 0x81, 0x73, 0x02, 0x2e, 0xec, 0x83,
	0x5e, 0x8b, 0x7d, 0x08, 0x5c, 0x26, 0x8d, 0x42, 0xa7, 0xfb, 0x75, 0x22, 0x8d, 0xf7, 0x60, 0xdc,
	0x76, 0xb3, 0x15, 0x96, 0x56, 0xc7, 0x63, 0x18, 0xce, 0x19, 0xab, 0xb6, 0x6b, 0xbc, 0x5b, 0x77,
	0xaf, 0xc7, 0xc6, 0x3e, 0xff, 0xec, 0x41, 0x78, 0xdb, 0x9c, 0x47, 0x7c, 0x78, 0xe0, 0xbb, 0xb0,
	0x98, 0xca, 0x4d, 0x2e, 0x2a, 0x7f, 0x5f, 0x73, 0x72, 0xb5, 0x55, 0xb6, 0xdd, 0xf6, 0x9f, 0x78,
	0x87, 0x7e, 0xbd, 0xa0, 0xb8, 0xdc, 0xf4, 0x99, 0xae, 0xe3, 0x64, 0xba, 0x4d, 0xf4, 0x67, 0x81,
	0xeb, 0xf0, 0xd1, 0x77, 0xfa, 0x53, 0xe0, 0x3e, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7,
	0xfa, 0x4e, 0xd3, 0x6d, 0x02, 0x00, 0x00,
}
