version: 1
snapshot:
  # Hide high-variability data from Percy snapshots; helps make sure that randomized data doesn't cause a visual diff.
  percy-css: | 
    table td { 
      visibility: hidden;
    }