name: Check Copywrite Headers

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'jrasell-test'

jobs:
  copywrite:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
        name: Setup Copywrite
        with:
          version: v0.25.3
          archive-checksum: e43f4b72fff3f219c5a5f883438d63edd5b68f5bea90a5d18abb3001c8c3aedc
      - name: Check Header Compliance
        run: make copywriteheaders
permissions:
  contents: read
