name: Check Copywrite Headers

on:
  push: {}

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: hashicorp/setup-copywrite@867a1a2a064a0626db322392806428f7dc59cb3e # v1.1.2
        name: Setup Copywrite
        with:
          version: v0.16.4
          archive-checksum: c299f830e6eef7e126a3c6ef99ac6f43a3c132d830c769e0d36fa347fa1af254
      - name: Check Header Compliance
        run: copywrite headers --plan
permissions:
  contents: read
